# Generated by Django 6.1.1 on 2026-09-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='selected_font',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
