# Generated by Django 6.1.1 on 2026-09-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0002_videoproject_selected_font'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('font_file_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KineticPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('badge_color', models.CharField(default='#F5A623', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Clip', max_length=200)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('font_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
